image: node:10.15.3

cache:
  paths:
    - node_modules/

stages:
  - lint
  - deploy_staging
  - test_reusable_deploy_script

lint:
  stage: lint
  script:
    - yarn install
    - yarn lint src
  only:
    - merge_requests

deploy_staging:
  stage: deploy_staging
  script:
    - wget https://firebasestorage.googleapis.com/v0/b/coursely-stg.appspot.com/o/aws-ec2-keys%2Fcommuly-api.pem?alt=media -O commuly-api.pem
    - chmod 400 commuly-api.pem
    - pwd
    - ls
    - ssh -i "commuly-api.pem" ec2-user@ec2-54-225-55-219.compute-1.amazonaws.com -o StrictHostKeyChecking=no "cd commuly-api && git pull origin development && wget https://firebasestorage.googleapis.com/v0/b/coursely-stg.appspot.com/o/environments%2Fenv?alt=media -O .env && pm2 restart all"
  only:
    # - tags
    - master
    # - development

test_reusable_deploy_script:
  stage: test_reusable_deploy_script
  script: ./scripts/deploy-to-cloud.sh
  only:
    - development