image: node:10.15.3

cache:
  paths:
    - node_modules/

stages:
  - lint

lint:
  stage: lint
  script:
    - yarn install
    - yarn lint src
  only:
    - tags
    - master
    - staging
    - merge_requests