const DONE_STATUS = 'DONE';
const STUCK_STATUS = 'STUCK';

const TODO_STATUS = [
  DONE_STATUS,
  STUCK_STATUS,
];

const PIN_USER = 'PIN_USER';
const UNPIN_USER = 'UNPIN_USER';

const RESPONSE_POINT = 5;
const REACTION_POINT = 3;
const PIN_POINT = 1;

const EMPLOYEE_ROLE = 'EMPLOYEE';
const SUPERVISOR_ROLE = 'SUPERVISOR';
const PROGRAM_ADMINISTRATOR_ROLE = 'PROGRAM ADMINISTRATOR';

const PINNED_CARD_PRIORITY = {
  [PROGRAM_ADMINISTRATOR_ROLE]: 1,
  [SUPERVISOR_ROLE]: 2,
  [EMPLOYEE_ROLE]: 3,
  NONE: 4,
};

const USER_ROLES = [
  EMPLOYEE_ROLE, SUPERVISOR_ROLE, PROGRAM_ADMINISTRATOR_ROLE,
];

module.exports = {
  PINNED_CARD_PRIORITY,

  DONE_STATUS,
  STUCK_STATUS,

  TODO_STATUS,

  PIN_USER,
  UNPIN_USER,

  REACTION_POINT,
  RESPONSE_POINT,
  PIN_POINT,

  EMPLOYEE_ROLE,
  SUPERVISOR_ROLE,
  PROGRAM_ADMINISTRATOR_ROLE,
  USER_ROLES,
};
