const ADD_SCHEDULE_TEAM = 'ADD_SCHEDULE_TEAM';
const ADD_TODO_TEAM = 'ADD_TODO_TEAM';
const PIN_CARD_TEAM = 'PIN_CARD_TEAM';
const UNPIN_CARD_TEAM = 'UNPIN_CARD_TEAM';

module.exports = {
  ADD_SCHEDULE_TEAM,
  ADD_TODO_TEAM,
  PIN_CARD_TEAM,
  UNPIN_CARD_TEAM,
};
